from pathlib import Path
p=Path('/home/ubuntu/sgnl-media-homepage/client/src/pages/Home.tsx')
s=p.read_text()
s=s.replace('const [menuOpen, setMenuOpen] = useState(false); const [bookingOpen, setBookingOpen] = useState(false); const [quizOpen, setQuizOpen] = useState(false); const [announcement, setAnnouncement] = useState(true);', 'const [menuOpen, setMenuOpen] = useState(false); const [bookingOpen, setBookingOpen] = useState(false); const [quizOpen, setQuizOpen] = useState(false); const [quizStep, setQuizStep] = useState(0); const [announcement, setAnnouncement] = useState(true);')
s=s.replace('const openBooking = () => setBookingOpen(true);', 'const openBooking = () => setBookingOpen(true); const startQuiz = () => { setQuizStep(0); setQuizOpen(true); };')
s=s.replace('setQuizOpen(true)', 'startQuiz()')
s=s.replace('const startQuiz = () => { setQuizStep(0); startQuiz(); };', 'const startQuiz = () => { setQuizStep(0); setQuizOpen(true); };')
old='<span className="eyebrow">SGNL Quiz</span><h2>Score your offer and lead magnet in 3 minutes.</h2><p>Answer three quick questions to see where your signal is strongest and where it is getting lost.</p><div className="quiz-question"><span>01 / 03</span><strong>What are you selling right now?</strong><button onClick={() => setQuizOpen(false)}>A service</button><button onClick={() => setQuizOpen(false)}>A product</button><button onClick={() => setQuizOpen(false)}>An idea</button></div>'
new='<span className="eyebrow">SGNL Quiz <b>{quizStep < 3 ? `${quizStep + 1} / 3` : "RESULT"}</b></span>{quizStep < 3 ? <><h2>{["What are you selling right now?", "Where does your best demand come from?", "What needs the most work?"][quizStep]}</h2><p>Answer three quick questions to see where your signal is strongest and where it is getting lost.</p><div className="quiz-progress"><i style={{ width: `${((quizStep) / 3) * 100}%` }} /></div><div className="quiz-question"><span>QUESTION 0{quizStep + 1} / 03</span>{(quizStep === 0 ? ["A service", "A product", "An idea"] : quizStep === 1 ? ["Referrals", "Content", "Paid media"] : ["Positioning", "Production", "Conversion"]).map(option => <button key={option} onClick={() => setQuizStep(quizStep + 1)}>{option}<ArrowUpRight size={15} /></button>)}</div></> : <div className="quiz-result"><span className="quiz-result-mark">SIGNAL FOUND</span><h2>Your next move is clearer.</h2><p>You have the raw signal. SGNL helps turn it into a repeatable media system behind your expertise.</p><button className="button lime" onClick={() => { setQuizOpen(false); openBooking(); }}>Book a call <ArrowUpRight size={16} /></button><button className="quiz-restart" onClick={startQuiz}>Retake quiz</button></div>}'
if old not in s: raise SystemExit('quiz markup not found')
s=s.replace(old,new)
p.write_text(s)
