import { useEffect, useRef, useState } from "react";
import { ArrowUpRight, CalendarDays, Check, ChevronLeft, ChevronRight, Menu, Play, Plus, Radio, Sparkles, X } from "lucide-react";
import { Link } from "wouter";

const process = [
  ["01", "Diagnose", "We start with a Signal Session to find what's holding your growth back and whether we're the right team to fix it."],
  ["02", "Build", "We build your brand system: your voice, recurring formats, visual identity, and the path from attention to booked calls."],
  ["03", "Capture", "You give us 90 minutes on camera once a month. We turn that into 25 to 30 pieces made for each platform."],
  ["04", "Scale", "Every month we tie your content to pipeline, not view count. We cut what isn't working and double down on what is."],
];

const tags = ["Organic first", "Paid behind proven creative", "Tested landing pages", "Monthly capture session", "Waterfall distribution", "Brand systems", "Lead magnets"];

function GrowthCard({ client, multiple, label, before, after }: { client: string; multiple: string; label: string; before: string; after: string }) {
  return <article className="case-card growth-card">
    <div className="chip-row"><span className="chip">{label}</span><span className="chip chip-lime">{multiple}</span></div>
    <div className="growth-number"><span>{before}</span><b>→</b><strong>{after}</strong></div>
    <div className="bar-stack">
      <div className="bar-label"><span>Before</span><b>{before}</b></div><div className="bar"><i className="bar-before" /></div>
      <div className="bar-label"><span>Now</span><b>{after}</b></div><div className="bar"><i className="bar-after" /></div>
    </div>
    <div className="card-footer"><span>{client === "Hardly Initiated" ? "We built the brand, the look and the edit style." : "Research first. Format tested. Attention into revenue."}</span><b>{client === "Hardly Initiated" ? "Still going viral daily" : "6 months with SGNL"}</b></div>
  </article>;
}

function StoryCard() {
  const [playing, setPlaying] = useState(false);
  return <article className="story-card">
    <div className="story-layout story-layout--single">
      <button className={`story-video ${playing ? "is-playing" : ""}`} type="button" onClick={() => setPlaying(true)} aria-label="Play Tysean client story">
        {playing ? <video src="/manus-storage/videoplayback(1)_835177cd.mp4" title="Tysean client story" controls autoPlay playsInline /> : <><video className="story-video-poster" src="/manus-storage/videoplayback(1)_835177cd.mp4" muted autoPlay loop playsInline /><span className="story-video-mark">HI</span><span className="play-button"><Play size={24} fill="currentColor" /></span><span className="story-video-caption">TYSEAN / HARDLY INITIATED</span></>}
      </button>
    </div>
  </article>;
}

function TestimonialPlaceholder({ number, label }: { number: string; label: string }) {
  return <article className="testimonial-placeholder"><span className="testimonial-placeholder-number">{number}</span><div className="testimonial-placeholder-icon"><Play size={20} fill="currentColor" /></div><span className="testimonial-placeholder-label">{label}</span><span className="testimonial-placeholder-note">Video coming soon</span></article>;
}

function ReelCard({ index, tone, video, label }: { index: string; tone: string; video?: string; label?: string }) {
  return <article className="reel-card"><div className={`reel-visual ${tone}`}>{video && <video className="reel-video" src={video} muted autoPlay loop playsInline />}<span className="reel-code">{index}</span><span className="reel-vertical">SGNL / MEDIA</span><span className="reel-scan" /><span className="reel-orb" /><span className="reel-play"><Play size={13} fill="currentColor" /></span></div><div className="reel-meta"><span>{video ? `${label ?? (index === "01" ? "June 3" : "July 2")} / Client reel` : "Client reel"}</span><ArrowUpRight size={15} /></div></article>;
}

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false); const [bookingOpen, setBookingOpen] = useState(false); const [quizOpen, setQuizOpen] = useState(false); const [quizStep, setQuizStep] = useState(0); const [quizAnswers, setQuizAnswers] = useState(["", "", ""]); const [quizEmail, setQuizEmail] = useState(""); const [announcement, setAnnouncement] = useState(true); const [selectedDate, setSelectedDate] = useState("Tue, Sep 22"); const [selectedTime, setSelectedTime] = useState("11:30 AM");
  const testimonialRef = useRef<HTMLDivElement>(null);
  useEffect(() => { document.body.style.overflow = menuOpen || bookingOpen || quizOpen ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [menuOpen, bookingOpen, quizOpen]);
  useEffect(() => { const track = testimonialRef.current; if (!track) return; let paused = false; const advance = () => { if (paused) return; const slide = track.querySelector<HTMLElement>(".testimonial-slide"); if (!slide) return; const step = slide.offsetWidth + 14; const atEnd = track.scrollLeft + track.clientWidth >= track.scrollWidth - 4; track.scrollTo({ left: atEnd ? 0 : track.scrollLeft + step, behavior: "smooth" }); }; const timer = window.setInterval(advance, 4200); const pause = () => { paused = true; }; const resume = () => { paused = false; }; track.addEventListener("mouseenter", pause); track.addEventListener("mouseleave", resume); track.addEventListener("touchstart", pause, { passive: true }); track.addEventListener("touchend", resume, { passive: true }); return () => { window.clearInterval(timer); track.removeEventListener("mouseenter", pause); track.removeEventListener("mouseleave", resume); track.removeEventListener("touchstart", pause); track.removeEventListener("touchend", resume); }; }, []);
  const openBooking = () => setBookingOpen(true); const startQuiz = () => { setQuizStep(0); setQuizAnswers(["", "", ""]); setQuizEmail(""); setQuizOpen(true); }; const quizResult = quizAnswers[2] === "Conversion" ? { title: "Your signal is leaking at conversion.", body: "Your positioning and production have a foundation. The next move is building a clearer path from attention to action.", focus: "Conversion system" } : quizAnswers[1] === "Content" ? { title: "Your strongest signal is already in content.", body: "You have the raw material for authority. The next move is turning consistent content into a repeatable demand system.", focus: "Content engine" } : quizAnswers[0] === "A product" ? { title: "Your product needs a sharper signal.", body: "The opportunity is making the value easier to understand, remember, and act on across every touchpoint.", focus: "Product positioning" } : { title: "Your expertise is ready for a system.", body: "You have the foundation. The next move is packaging your point of view into a media system that compounds.", focus: "Authority system" }; const downloadQuiz = () => { const text = `SGNL QUIZ RESULTS\n\n${quizResult.title}\n${quizResult.body}\n\nFocus: ${quizResult.focus}\nAnswers: ${quizAnswers.join(" / ")}`; const safe = text.replace(/[()\\]/g, "\\$&").split("\n").map(line => `(${line}) Tj 0 -14 Td`).join("\n"); const pdf = `%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n2 0 obj<</Type/Pages/Count 1/Kids[3 0 R]>>endobj\n3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Resources<</Font<</F1 4 0 R>>>>/Contents 5 0 R>>endobj\n4 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj\n5 0 obj<</Length ${safe.length + 35}>>stream\nBT /F1 11 Tf 54 740 Td ${safe} ET\nendstream endobj\ntrailer<</Root 1 0 R>>\n%%EOF`; const blob = new Blob([pdf], { type: "application/pdf" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "sgnl-quiz-results.pdf"; link.click(); URL.revokeObjectURL(url); }; const shareQuiz = async () => { const text = `My SGNL quiz result: ${quizResult.title}`; if (navigator.share) await navigator.share({ title: "My SGNL quiz result", text, url: window.location.href }); else { await navigator.clipboard?.writeText(`${text} ${window.location.href}`); window.alert("Result link copied to your clipboard."); } };
  const closeMenu = () => setMenuOpen(false);
  return <div className="site-shell" id="top">
    {announcement && <div className="announcement-bar"><button onClick={() => startQuiz()}>Free tool: score your offer and lead magnet in 3 minutes <span>Take the quiz ↗</span></button><button aria-label="Dismiss announcement" onClick={() => setAnnouncement(false)}><X size={14} /></button></div>}
      <header className="site-header"><a href="#top" className="wordmark">SGNL <span>Media</span></a><nav><a href="#top">Home</a><i>/</i><Link href="/shows">Shows</Link><i>/</i><a href="#services">Services</a></nav><div className="header-actions"><button className="header-cta" onClick={openBooking}>Book a call <ArrowUpRight size={15} /></button><button className="menu-trigger" onClick={() => setMenuOpen(true)} aria-label="Open menu"><Menu size={21} /></button></div></header>
    {menuOpen && <div className="mobile-menu"><div className="mobile-menu-top"><span className="eyebrow">Menu</span><button onClick={closeMenu}><X size={19} /></button></div><div className="mobile-links"><a href="#top" onClick={closeMenu}>Home <ArrowUpRight size={18} /></a><Link href="/shows" onClick={closeMenu}>Shows <ArrowUpRight size={18} /></Link><a href="#services" onClick={closeMenu}>Services <ArrowUpRight size={18} /></a><button onClick={() => { closeMenu(); startQuiz(); }}>Take the quiz <ArrowUpRight size={18} /></button></div><button className="mobile-book" onClick={() => { closeMenu(); openBooking(); }}>Book a call <ArrowUpRight size={16} /></button></div>}
    <main>
      <section className="hero section-rule"><div className="hero-glow" aria-hidden="true" /><div className="hero-split"><div className="hero-copy"><h1 className="hero-reveal hero-reveal--headline">We build the media teams behind category-leading brands and experts.</h1><p className="hero-subline hero-reveal hero-reveal--subline">Positioning, production, distribution, and conversion infrastructure—built to turn real expertise into authority, demand, and pipeline.</p><div className="hero-actions hero-reveal hero-reveal--actions"><button className="button lime" onClick={() => startQuiz()}>Take the quiz <ArrowUpRight size={16} /></button><button className="button ghost" onClick={openBooking}>Book a call <ArrowUpRight size={16} /></button></div><div className="hero-mobile-reels hero-reveal hero-reveal--reel"><div className="hero-mobile-reels-track"><div className="hero-mobile-reel"><video src="/manus-storage/June3_8566eb30.mp4" muted autoPlay loop playsInline /><span>June 3 / Client reel</span></div><div className="hero-mobile-reel"><video src="/manus-storage/July2_5a535c6c.mp4" muted autoPlay loop playsInline /><span>July 2 / Client reel</span></div></div></div></div><div className="hero-reel hero-reveal hero-reveal--reel"><div className="hero-reel-frame"><video src="/manus-storage/June3_8566eb30.mp4" muted autoPlay loop playsInline /><div className="hero-reel-overlay" /><span className="hero-reel-kicker">CLIENT WORK / 01—02</span><span className="hero-reel-label">SGNL / MEDIA</span><span className="hero-reel-scan" /><span className="hero-reel-play"><Play size={16} fill="currentColor" /></span></div><div className="hero-reel-meta"><span>Recent work</span><span>June 3 — July 2 <ArrowUpRight size={14} /></span></div></div></div></section>
      <section className="reels section-rule" id="shows"><div className="section-head"><div><span className="eyebrow">Recent work</span><h2>Content that<br /><em>finds the right audience.</em></h2></div><span className="section-count">01—04</span></div><div className="reel-track"><ReelCard index="01" tone="tone-one" video="/manus-storage/June3_8566eb30.mp4" label="June 3" /><ReelCard index="02" tone="tone-two" video="/manus-storage/July2_5a535c6c.mp4" label="July 2" /><ReelCard index="03" tone="tone-three" video="/manus-storage/A-P-11_52388ec7.mp4" label="A–P 11" /><ReelCard index="04" tone="tone-one" video="/manus-storage/S-T-2_a0a4c032.mp4" label="S–T 2" /></div></section>
      <section className="manifesto section-rule"><div className="manifesto-label"><span className="eyebrow">What we believe</span><Sparkles size={17} /></div><h2>Great brands and experts don't need another content vendor. They need a marketing team that knows what works and can prove it.</h2></section>
      <section className="process section-rule" id="services"><div className="section-head"><div><span className="eyebrow">Four steps</span><h2>How we build<br /><em>your marketing team.</em></h2></div><div className="signal-bars"><i /><i /><i /><i /><i /></div></div><div className="process-list">{process.map(([num, title, body]) => <article className="process-step" key={num}><span className="process-number">{num}</span><h3>{title}</h3><p>{body}</p><span className="process-plus"><Plus size={17} /></span></article>)}</div><button className="button outline" onClick={openBooking}>Book a Signal Session <ArrowUpRight size={16} /></button></section>
      <section className="results section-rule" id="results"><div className="results-intro"><h2>Proof over<br /><em>promises.</em></h2><p>Real accounts, real numbers. Here's what happens when a brand finally gets a system behind its content.</p></div><div className="testimonial-track" ref={testimonialRef}><div className="testimonial-slide"><StoryCard /></div><div className="testimonial-slide"><TestimonialPlaceholder number="02" label="Client story / 02" /></div><div className="testimonial-slide"><TestimonialPlaceholder number="03" label="Client story / 03" /></div></div></section>
      <section className="closing section-rule"><span className="closing-spark"><Sparkles size={27} /></span><h2>We'd love to partner with you <em>& your team.</em></h2><button className="button lime large" onClick={openBooking}>Book a call <ArrowUpRight size={17} /></button></section>
    </main>
    <footer className="footer"><div className="footer-main"><div><a href="#top" className="wordmark">SGNL <span>Media</span></a><p>We build marketing teams behind brands and experts.</p></div><div className="footer-links"><div><b>Company</b><a href="#top">Home</a><a href="#services">Services</a><a href="#shows">Shows</a></div><div><b>Shows</b><a href="#shows">Read the room</a><a href="#shows">What is marketing?</a><a href="#shows">SGNL CEO</a></div><div><b>Start</b><button onClick={() => startQuiz()}>Take the quiz</button><button onClick={openBooking}>Book a call</button></div></div></div><div className="footer-bottom"><span>© 2026 SGNL Media. Tampa, FL.</span><span>Privacy&nbsp;&nbsp;/&nbsp;&nbsp; Terms</span></div></footer>
    {bookingOpen && <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && setBookingOpen(false)}><section className="modal-card cal-modal" role="dialog" aria-modal="true" aria-label="Book a call"><button className="modal-close" onClick={() => setBookingOpen(false)}><X size={18} /></button><iframe src="https://cal.com/andrew-moullin-qldwj3/content-engine-strategy-call?layout=month_view&useSlotsViewOnSmallScreen=true" title="Book a content engine strategy call" /></section></div>}
    {quizOpen && <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && setQuizOpen(false)}><section className="modal-card" role="dialog" aria-modal="true" aria-label="SGNL quiz"><button className="modal-close" onClick={() => setQuizOpen(false)}><X size={18} /></button><span className="eyebrow">SGNL Quiz <b>{quizStep < 3 ? `${quizStep + 1} / 3` : quizStep === 3 ? "EMAIL" : "RESULT"}</b></span>{quizStep < 3 ? <><h2>{["What are you selling right now?", "Where does your best demand come from?", "What needs the most work?"][quizStep]}</h2><p>Answer three quick questions to see where your signal is strongest and where it is getting lost.</p><div className="quiz-progress"><i style={{ width: `${(quizStep / 3) * 100}%` }} /></div><div className="quiz-question"><span>QUESTION 0{quizStep + 1} / 03</span>{(quizStep === 0 ? ["A service", "A product", "An idea"] : quizStep === 1 ? ["Referrals", "Content", "Paid media"] : ["Positioning", "Production", "Conversion"]).map(option => <button key={option} onClick={() => { const next = [...quizAnswers]; next[quizStep] = option; setQuizAnswers(next); setQuizStep(quizStep + 1); }}>{option}<ArrowUpRight size={15} /></button>)}</div></> : quizStep === 3 ? <form className="quiz-email" onSubmit={e => { e.preventDefault(); if (quizEmail.trim()) setQuizStep(4); }}><h2>Where should we send your signal?</h2><p>Enter your email to unlock your personalized result and a downloadable copy.</p><label>Email address<input type="email" value={quizEmail} onChange={e => setQuizEmail(e.target.value)} placeholder="you@company.com" required /></label><button className="button lime" type="submit">Reveal my result <ArrowUpRight size={16} /></button><small>We’ll only use this to send your result.</small></form> : <div className="quiz-result"><span className="quiz-result-mark">SIGNAL FOUND / {quizResult.focus}</span><h2>{quizResult.title}</h2><p>{quizResult.body}</p><div className="quiz-result-actions"><button className="button lime" onClick={() => { setQuizOpen(false); openBooking(); }}>Book a call <ArrowUpRight size={16} /></button><button className="quiz-share" onClick={downloadQuiz}>Download PDF</button><button className="quiz-share" onClick={shareQuiz}>Share result</button></div><button className="quiz-restart" onClick={startQuiz}>Retake quiz</button></div>}</section></div>}
  </div>;
}
