import { ArrowUpRight } from "lucide-react";
import { useLocation } from "wouter";

const data = {
  "/shows/read-the-room": { style: "room", kicker: "Read the room / Issue 01", title: "The market is telling you what it wants. Are you listening?", subhead: "A weekly field note on language, timing, and the signals that move a category before the numbers catch up.", sections: [["The signal", "The strongest companies do not wait for a market to explain itself. They listen for the phrase a customer repeats, the workaround they have normalized, and the objection that keeps appearing in the room."], ["The read", "This week, attention is not scarce. Confidence is. The brands gaining ground are the ones making a precise promise and proving it in public."], ["The move", "Name the tension your buyer is already carrying. Then build the simplest useful response around it." ]] },
  "/shows/what-is-marketing": { style: "lecture", kicker: "What is marketing? / Lecture 04", title: "Marketing is a system for making belief easier.", subhead: "A lecture series on positioning, distribution, and the operating choices that turn attention into demand.", sections: [["The premise", "Marketing is not the decoration around a business. It is the system that makes the business legible to the people it is built to serve."], ["The distinction", "Promotion asks for attention. Strategy earns a place in memory. The difference is a point of view that survives contact with the market."], ["The practice", "Find the smallest repeatable act that makes your expertise more obvious. Then make it often enough to become evidence." ]] },
  "/shows/sgnl-ceo": { style: "ceo", kicker: "SGNL CEO / Conversation 07", title: "The founder's real job is to make the next decision clearer.", subhead: "Long-form conversations with the people building durable companies, systems, and categories.", sections: [["The question", "What changes when a founder stops being the source of every answer and starts designing the conditions for better answers?"], ["The pattern", "The best operators are not louder than the market. They are closer to the work. Their advantage is a higher resolution view of what is actually happening."], ["The takeaway", "Authority is not a performance. It is the residue of making sound decisions in public, over time." ]] },
} as const;

export default function ShowArticle() {
  const [location] = useLocation(); const article = data[location as keyof typeof data] ?? data["/shows/read-the-room"];
  return <main className={`show-article show-article--${article.style}`}><header className="show-article-header"><a href="/shows" className="editorial-mark">SGNL <span>Media</span></a><span>{article.kicker}</span><a href="/shows">All shows <ArrowUpRight size={14} /></a></header><div className="show-article-top"><span className="show-article-kicker">{article.kicker}</span><h1>{article.title}</h1><p>{article.subhead}</p><div className="show-article-meta">SGNL Media <span>·</span> September 2026 <span>·</span> 8 min read</div></div><div className="show-article-rule" /><article className="show-article-body">{article.sections.map(([title, body], index) => <section key={title}><span>0{index + 1}</span><div><h2>{title}</h2><p>{body}</p></div></section>)}<div className="show-article-end"><span>End of dispatch</span><ArrowUpRight size={17} /></div></article></main>;
}
